
services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "${POSTGRES_PORT:-20902}:5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "${MAILPIT_SMTP_PORT:-20906}:1025"
      - "${MAILPIT_HTTP_PORT:-20907}:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

###> symfony/messenger with rabbitmq ###
  rabbitmq:
    ports:
      - "${RABBITMQ_PORT:-20908}:5672" # AMQP protocol
      - "${RABBITMQ_MANAGEMENT_PORT:-20909}:15672" # Management UI
###< symfony/messenger with rabbitmq ###

  varnish:
    ports:
      - "${VARNISH_PORT:-20901}:80"

  redis:
    ports:
      - "${REDIS_PORT:-20903}:6379"
