services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "${POSTGRES_EXPOSED_PORT:-20902}:5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    container_name: en_shop_service_identity_mailer
    image: axllent/mailpit
    ports:
      - "${MAILPIT_SMTP_EXPOSED_PORT:-20906}:1025"
      - "${MAILPIT_HTTP_EXPOSED_PORT:-20907}:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

###> symfony/messenger with rabbitmq ###
  rabbitmq:
    ports:
      - "${RABBITMQ_EXPOSED_PORT:-20908}:5672" # AMQP protocol
      - "${RABBITMQ_MANAGEMENT_EXPOSED_PORT:-20909}:15672" # Management UI
###< symfony/messenger with rabbitmq ###

  nginx:
    ports:
      - "${NGINX_EXPOSED_PORT:-20900}:80"

  varnish:
    ports:
      - "${VARNISH_EXPOSED_PORT:-20901}:80"

  redis:
    ports:
      - "${REDIS_EXPOSED_PORT:-20903}:6379"
