<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260806120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add Doctrine outbox for domain events and the idempotency ledger.';
    }

    public function up(Schema $schema): void
    {
        // Outbox et files d'échec Messenger (domain_events, failed_async, failed_domain_events).
        // Créée par migration et non
        // par auto_setup : en Postgres le DDL est transactionnel, un auto-setup déclenché
        // pendant une transaction métier disparaîtrait avec un rollback.
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');

        // Inbox : une ligne par couple (événement, handler) déjà traité.
        $this->addSql('CREATE TABLE processed_domain_event (event_id VARCHAR(32) NOT NULL, handler VARCHAR(255) NOT NULL, processed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(event_id, handler))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE processed_domain_event');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
