<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260201120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Align refresh_tokens.id with IDENTITY generation';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE refresh_tokens ALTER COLUMN id DROP IDENTITY IF EXISTS');
        $this->addSql('ALTER TABLE refresh_tokens ALTER COLUMN id DROP DEFAULT');
        $this->addSql('ALTER TABLE refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE refresh_tokens ALTER COLUMN id DROP IDENTITY IF EXISTS');
        $this->addSql('ALTER TABLE refresh_tokens ALTER COLUMN id SET DEFAULT nextval(\'refresh_tokens_id_seq\')');
    }
}
